In [2]:
import numpy as np
import pandas as pd

In [3]:
import sys
# Get py version
'.'.join(map(str, sys.version_info[:2]))

'3.9'

## Numpy arrays

In [33]:
# Vector
lst = range(1, 4)
arr = np.array(lst)
print(arr)

[1 2 3]


In [37]:
# Matrix
lst2 = [range(1, 4), range(4, 7)]
arr2 = np.array(lst2)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [41]:
# Decrese all values by 2, simultaneously
someprices = np.array(range(5, 10))
decrby2 = someprices - 2
print(decrby2)

[3 4 5 6 7]


## Pandas Series and Dataframes

In [59]:
ages = np.array([13, 25, 18])
# default indexes, 0 1 2 ...
series = pd.Series(ages)
print(series, '\n')

# keys indexes
series = pd.Series(ages, index=['Nikita', 'Sasha', 'Marsel'])
print(series)

0    13
1    25
2    18
dtype: int64 

Nikita    13
Sasha     25
Marsel    18
dtype: int64


In [68]:
df = pd.DataFrame([
    ['John Smith','123 Main St',34],
    ['Jane Doe', '456 Maple Ave',28],
    ['Joe Schmo', '789 Broadway',51]
],
    columns=['name', 'address', 'age'])

In [69]:
df

name        address  age
0  John Smith    123 Main St   34
1    Jane Doe  456 Maple Ave   28
2   Joe Schmo   789 Broadway   51

In [70]:
# change default index(1 2 3) to 
df.set_index('name')

address  age
name                          
John Smith    123 Main St   34
Jane Doe    456 Maple Ave   28
Joe Schmo    789 Broadway   51

Some methods

In [32]:
# create vector
# int64 by default
zeros_vector = np.zeros(10, dtype=int)
zeros_vector.dtype

dtype('int64')

In [34]:
# create matrix
ones_matrix = np.ones((5, 5), dtype=float)
ones_matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
# create matrix with custom value
matrix_sq = np.full((4, 4), 0.451)
matrix_sq

array([[0.451, 0.451, 0.451, 0.451],
       [0.451, 0.451, 0.451, 0.451],
       [0.451, 0.451, 0.451, 0.451],
       [0.451, 0.451, 0.451, 0.451]])

In [39]:
# create arr with set sequence
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [42]:
# create arr of even space between the given range of vals
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [49]:
# create matrix with mean 0 and standard deviation 1 in given dimension
np.random.normal(0, 1, (4, 4))

array([[-0.62582912,  0.13742332, -0.25255784, -1.15107454],
       [ 0.18036263, -0.70802793, -0.09512902, -0.63810796],
       [ 0.83657546,  0.55576596, -0.3160832 ,  0.93331803],
       [-1.41893258, -0.77126975,  1.09935215, -1.34584371]])

In [61]:
# create indentity matrix
np.eye(3, 3, 0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
# set random seed
np.random.seed(0)

In [85]:
# verctor
x1 = np.random.randint(10, size=6)
x1

array([0, 4, 9, 0, 6, 4])

In [86]:
# two dimension
x2 = np.random.randint(10, size=(4, 4))
x2

array([[2, 4, 6, 3],
       [3, 7, 8, 5],
       [0, 8, 5, 4],
       [7, 4, 1, 3]])

In [88]:
# three dimension
x3 = np.random.randint(10, size=(4, 4, 4))
x3

array([[[9, 6, 0, 3],
        [8, 4, 1, 4],
        [5, 0, 3, 1],
        [4, 4, 4, 0]],

       [[0, 8, 4, 6],
        [9, 3, 3, 2],
        [1, 2, 1, 3],
        [4, 1, 1, 0]],

       [[7, 8, 4, 3],
        [5, 6, 3, 2],
        [9, 8, 1, 4],
        [0, 8, 3, 9]],

       [[5, 5, 1, 7],
        [8, 6, 4, 7],
        [3, 5, 3, 6],
        [4, 7, 3, 0]]])

In [89]:
for i in x3:
    print('i', i)
    for j in i:
        print('j', j)
    print()

i [[9 6 0 3]
 [8 4 1 4]
 [5 0 3 1]
 [4 4 4 0]]
j [9 6 0 3]
j [8 4 1 4]
j [5 0 3 1]
j [4 4 4 0]

i [[0 8 4 6]
 [9 3 3 2]
 [1 2 1 3]
 [4 1 1 0]]
j [0 8 4 6]
j [9 3 3 2]
j [1 2 1 3]
j [4 1 1 0]

i [[7 8 4 3]
 [5 6 3 2]
 [9 8 1 4]
 [0 8 3 9]]
j [7 8 4 3]
j [5 6 3 2]
j [9 8 1 4]
j [0 8 3 9]

i [[5 5 1 7]
 [8 6 4 7]
 [3 5 3 6]
 [4 7 3 0]]
j [5 5 1 7]
j [8 6 4 7]
j [3 5 3 6]
j [4 7 3 0]



In [94]:
print(f'ndim = {x3.ndim}, shape = {x3.shape}, size = {x3.size}')

ndim = 3, shape = (4, 4, 4), size = 64


pandas!

In [98]:
d = {
    'Country': ['Russia', 'Colombia', 'Chile', 'Equador', 'Nigeria'],
    'Rank': [121, 40, 100, 130, 11]
}

df = pd.DataFrame(d)
df

Country  Rank
0    Russia   121
1  Colombia    40
2     Chile   100
3   Equador   130
4   Nigeria    11

In [99]:
# Get a quick analysis of data
df.describe()

Rank
count    5.000000
mean    80.400000
std     52.300096
min     11.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000

In [102]:
# Get complete info about data set
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Country  5 non-null      object
 1   Rank     5 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes


In [119]:
d = {
    'group': ['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],
    'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]
}

df = pd.DataFrame(d)
df

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [121]:
# inplace = True will make change to the df
df.sort_values(by=['ounces'], ascending=True, inplace=False)

group  ounces
1     a     3.0
6     c     3.0
0     a     4.0
7     c     5.0
3     b     6.0
8     c     6.0
4     b     7.5
5     b     8.0
2     a    12.0

In [126]:
# sort by multiple columns
df.sort_values(
    by=['group', 'ounces'], ascending=[True, False], inplace=False)

group  ounces
2     a    12.0
0     a     4.0
1     a     3.0
5     b     8.0
4     b     7.5
3     b     6.0
8     c     6.0
7     c     5.0
6     c     3.0

In [129]:
d = {
    'k1': ['one']*3 + ['two']*4,
    'k2':[3,2,1,3,3,4,4]
}

df = pd.DataFrame(d)
df

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4

In [130]:
# sort
df.sort_values(by='k2')

k1  k2
2  one   1
1  one   2
0  one   3
3  two   3
4  two   3
5  two   4
6  two   4

In [132]:
# remove duplicates
df.drop_duplicates().sort_values(by='k2')

k1  k2
2  one   1
1  one   2
0  one   3
3  two   3
5  two   4

In [133]:
# remove duplicates based on particular column
df.drop_duplicates(subset='k1')

k1  k2
0  one   3
3  two   3

In [136]:
s = pd.Series([1., -999., 2., -999., -1000., 3.])
s

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [139]:
s.replace(-999, np.nan, inplace=True)
s

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [149]:
i = ['Ohio', 'Colorado', 'New York']
c = ['one', 'two', 'three', 'four']

df = pd.DataFrame(np.arange(12).reshape((3, 4)), index=i, columns=c)
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [150]:
df.rename(index={'Ohio': 'SanF'}, columns={'one': 'one_p'}, inplace=True)
df

one_p  two  three  four
SanF          0    1      2     3
Colorado      4    5      6     7
New York      8    9     10    11

In [152]:
df.rename(index = str.upper, inplace=True)
df

one_p  two  three  four
SANF          0    1      2     3
COLORADO      4    5      6     7
NEW YORK      8    9     10    11

In [157]:
# Categorize (bin) vars
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

In [159]:
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [161]:
pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [162]:
bin_names = ['Youth', 'YoungAdult', 'MiddleAge', 'Senior']
ncats = pd.cut(ages, bins, labels=bin_names)

pd.value_counts(ncats)

Youth         5
YoungAdult    3
MiddleAge     3
Senior        1
dtype: int64