In [25]:
import numpy as np
import pandas as pd

In [71]:
import sys
# Get py version
'.'.join(map(str, sys.version_info[:2]))

'3.9'

## Numpy arrays

In [33]:
# Vector
lst = range(1, 4)
arr = np.array(lst)
print(arr)

[1 2 3]


In [37]:
# Matrix
lst2 = [range(1, 4), range(4, 7)]
arr2 = np.array(lst2)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [41]:
# Decrese all values by 2, simultaneously
someprices = np.array(range(5, 10))
decrby2 = someprices - 2
print(decrby2)

[3 4 5 6 7]


## Pandas Series and Dataframes

In [59]:
ages = np.array([13, 25, 18])
# default indexes, 0 1 2 ...
series = pd.Series(ages)
print(series, '\n')

# keys indexes
series = pd.Series(ages, index=['Nikita', 'Sasha', 'Marsel'])
print(series)

0    13
1    25
2    18
dtype: int64 

Nikita    13
Sasha     25
Marsel    18
dtype: int64


In [68]:
df = pd.DataFrame([
    ['John Smith','123 Main St',34],
    ['Jane Doe', '456 Maple Ave',28],
    ['Joe Schmo', '789 Broadway',51]
],
    columns=['name', 'address', 'age'])

In [69]:
df

name        address  age
0  John Smith    123 Main St   34
1    Jane Doe  456 Maple Ave   28
2   Joe Schmo   789 Broadway   51

In [70]:
# change default index(1 2 3) to 
df.set_index('name')

address  age
name                          
John Smith    123 Main St   34
Jane Doe    456 Maple Ave   28
Joe Schmo    789 Broadway   51